language: node_js
sudo: required
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
node_js: stable
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run wct
